### ISSUE TITLE
Can we improve the formatting on the sphinx docs ?

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#190]
I don't know how easy it is to add or change the CSS for the sphinx docs, but it could be worthwhile

For instance, just dropping the extra indentation in the code blocks (making everything 8px, and making the headers full width, looks quite a bit better to me).

This was just prototyped in the browser using inspect-element

Before
![image](https://user-images.githubusercontent.com/179677/51331992-cbd77600-1a72-11e9-9b6d-4522e284a3fc.png)

After
![image](https://user-images.githubusercontent.com/179677/51332479-b9aa0780-1a73-11e9-96ea-e169d312aa9d.png)

On the other hand, maybe there is just a newer theme we can use somewhere.

**Comment by stuaxo** [comment]
https://stackoverflow.com/questions/23211695/modifying-content-width-of-the-sphinx-theme-read-the-docs

**Comment by stuaxo** [comment]
Playing with some overrides:

```css
.rst-content blockquote {
    margin-left: 0 !important;
}

.rst-content table {
    width: 100%;
}
```
